##########################################################################################
# +------------------------------------------------------------------------------------+ #
# |       ____      _                 _        ____             __ _                   | #
# |      / ___|___ | |____      _____| |__    / ___|___  _ __  / _(_) __ _             | #
# |     | |   / _ \| '_ \ \ /\ / / _ \ '_ \  | |   / _ \| '_ \| |_| |/ _` |            | #
# |     | |__| (_) | |_) \ V  V /  __/ |_) | | |__| (_) | | | |  _| | (_| |            | #
# |      \____\___/|_.__/ \_/\_/ \___|_.__/   \____\___/|_| |_|_| |_|\__, |            | #
# |                                                                  |___/             | #
# |                                                                                    | #
# |                           A complete plugin for boxpvp                             | #
# |                                                                                    | #
# |                      © 2024 - Developed by retiredbydavid                          | #
# |                                                                                    | #
# |                                                                                    | #
# |                                                                                    | #
# |                       Configure the plugin to your liking.                         | #
# +------------------------------------------------------------------------------------+ #
##########################################################################################

##########################################
#                                        #
#            Configuración               #
#                                        #
##########################################

cobweb:
  # Define si el plugin estara activado o no.
  # Si esta en true las telarañas desapareceran.
  # Si esta en false las telarañas no desapareceran.
  enable: true
  # Delay: Tiempo en el cual las telarañas desaparecenran.
  # Establece un valor entero.
  # 1 = 1s
  # 10 = 10s
  # 20 = 20s ......
  delay: 10

wool:
  material: GREEN_WOOL
  enable: true
  delay: 10

regions:
  mode: "blacklist" # Can be "blacklist" or "whitelist"
  list:
    - "spawn"
    - "pvp_arena"
  message: "§cNo puedes colocar telarañas en esta región."

  ##################################
  #                                #
  #         FIN // Acabo           #
  ##################################